# Generated by Django 3.1.1 on 2020-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_it',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='post_it',
            name='left',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='post_it',
            name='top',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='post_it',
            name='width',
            field=models.FloatField(),
        ),
    ]
