# Generated by Django 3.1.1 on 2020-10-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_it', '0002_auto_20201002_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_it',
            name='zindex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
