# Generated by Django 3.1.2 on 2020-11-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_it', '0003_post_it_zindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_id',
        ),
    ]
