# Generated by Django 3.1.2 on 2020-11-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_it', '0004_remove_session_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
