# Generated by Django 3.1.2 on 2020-11-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_it', '0005_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
