# Generated by Django 3.1.2 on 2020-12-17 15:34

from django.db import migrations, models
import post_it.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_it', '0006_auto_20201129_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='code',
            field=models.CharField(default=post_it.models.generate_code, max_length=10, unique=False),
        ),
    ]
