# Generated by Django 3.1.2 on 2020-12-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_it', '0008_auto_20201217_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='code',
            new_name='session_code',
        ),
    ]
