# Generated by Django 3.1.2 on 2020-12-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_it', '0011_auto_20201231_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_it',
            name='htmlId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
